#!/usr/bin/env python3
# See COPYING.txt for license details.
"""
gen_nice_flor_s_table_builtin.py — Embed the Nice FloR-S rainbow table into M1 firmware.

Reads a 32-byte rainbow table expressed as a hex string (64 hex characters)
and generates Sub_Ghz/subghz_nice_flor_s_table_builtin.c containing the
table as a ``const uint8_t[32]`` array compiled directly into the firmware
binary.

This mirrors the KeeLoq manufacturer-key injection approach: the table is
baked into the firmware at build time via a GitHub Actions secret, never
stored on removable media, and never appears in the public repository.

When no hex string is provided (or the string is invalid), generates a
stub with NULL/zero data — callers fall back to "table?" placeholders.

Usage
-----
::

    # With a private rainbow table (64 hex chars):
    python3 scripts/gen_nice_flor_s_table_builtin.py \\
        --hex "0123456789ABCDEF...32 bytes..." \\
        Sub_Ghz/subghz_nice_flor_s_table_builtin.c

    # From environment variable:
    export NICE_FLOR_S_RAINBOW_TABLE="0123456789ABCDEF..."
    python3 scripts/gen_nice_flor_s_table_builtin.py \\
        Sub_Ghz/subghz_nice_flor_s_table_builtin.c

    # Regenerate the NULL stub (public/CI without secret):
    python3 scripts/gen_nice_flor_s_table_builtin.py \\
        Sub_Ghz/subghz_nice_flor_s_table_builtin.c
"""

import argparse
import os
import sys

NICE_FLOR_S_TABLE_SIZE = 32   # bytes

# ---------------------------------------------------------------------------
# C source generators
# ---------------------------------------------------------------------------

_STUB_TEMPLATE = """\
/* See COPYING.txt for license details. */

/**
 * @file  subghz_nice_flor_s_table_builtin.c
 * @brief Nice FloR-S rainbow table embedded at build time.
 *
 * This stub version contains no table data and is the version committed
 * to the public repository.  At build time,
 * scripts/gen_nice_flor_s_table_builtin.py regenerates this file from
 * the NICE_FLOR_S_RAINBOW_TABLE environment variable (or GitHub Actions
 * secret).
 *
 * When this file contains a real table:
 *   - The scene handler and signal-fields code use it directly from
 *     firmware flash to decrypt/re-encrypt Nice FloR-S payloads.
 *   - No SD card file is consulted (same approach as KeeLoq builtin
 *     keys).
 *
 * When this file contains the stub (len == 0):
 *   - Counter and serial fields show "table?" placeholders.
 *   - This is the behaviour for public/CI builds without the secret.
 *
 * DO NOT commit a version of this file that contains a real rainbow
 * table.  The generator script overwrites this file in-place during
 * private builds; only the NULL stub version ever appears in the
 * public repository.
 */

#include <stddef.h>
#include "subghz_nice_flor_s_table_builtin.h"

/* No table embedded — callers will show "table?" placeholders. */
const uint8_t * const nice_flor_s_table_builtin     = NULL;
const uint32_t        nice_flor_s_table_builtin_len  = 0;
"""


def _format_table_row(data, offset, count):
    """Format *count* bytes starting at *offset* as hex C initializers."""
    return ', '.join(f'0x{data[offset + i]:02X}' for i in range(count))


def generate_populated_source(table_bytes):
    """Generate a C source file embedding *table_bytes* (32 bytes)."""
    row1 = _format_table_row(table_bytes, 0, 16)
    row2 = _format_table_row(table_bytes, 16, 16)

    return f"""\
/* See COPYING.txt for license details. */

/**
 * @file  subghz_nice_flor_s_table_builtin.c
 * @brief Nice FloR-S rainbow table embedded at build time — 32 bytes.
 *
 * AUTO-GENERATED by scripts/gen_nice_flor_s_table_builtin.py
 *
 * DO NOT COMMIT this file with a real rainbow table to the public
 * repository.  The committed version of this file is a NULL stub.
 * This generated version is used only during private/CI builds.
 */

#include <stddef.h>
#include "subghz_nice_flor_s_table_builtin.h"

static const uint8_t s_nice_flor_s_table[{NICE_FLOR_S_TABLE_SIZE}] = {{
    {row1},
    {row2},
}};

const uint8_t * const nice_flor_s_table_builtin     = s_nice_flor_s_table;
const uint32_t        nice_flor_s_table_builtin_len  = {NICE_FLOR_S_TABLE_SIZE};
"""


# ---------------------------------------------------------------------------
# Hex string parser
# ---------------------------------------------------------------------------

def parse_hex_table(hex_str):
    """Parse a hex string into exactly 32 bytes.

    Accepts optional separators (spaces, commas, colons, 0x prefixes).
    Returns bytes or None on failure.
    """
    if not hex_str:
        return None
    # Strip common separators and 0x prefixes
    cleaned = hex_str.strip()
    cleaned = cleaned.replace(' ', '').replace(',', '').replace(':', '')
    cleaned = cleaned.replace('0x', '').replace('0X', '')
    cleaned = cleaned.replace('\\n', '').replace('\\r', '')
    try:
        raw = bytes.fromhex(cleaned)
    except ValueError:
        return None
    if len(raw) != NICE_FLOR_S_TABLE_SIZE:
        return None
    return raw


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(
        description=(
            "Embed the Nice FloR-S rainbow table into M1 firmware at build time.\n\n"
            "Provide a 32-byte table as 64 hex characters via --hex or the\n"
            "NICE_FLOR_S_RAINBOW_TABLE environment variable.\n\n"
            "Without a table: generates a NULL stub — counter/serial show 'table?'.\n\n"
            "Output always replaces Sub_Ghz/subghz_nice_flor_s_table_builtin.c.\n"
            "DO NOT commit the populated version to the public repository."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--hex",
        default=None,
        help=(
            "32-byte rainbow table as 64 hex characters.  "
            "If omitted, falls back to the NICE_FLOR_S_RAINBOW_TABLE env var."
        ),
    )
    parser.add_argument(
        "output",
        nargs="?",
        default=os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "Sub_Ghz",
            "subghz_nice_flor_s_table_builtin.c",
        ),
        help=(
            "Output C source file path "
            "(default: Sub_Ghz/subghz_nice_flor_s_table_builtin.c relative to repo root)"
        ),
    )
    args = parser.parse_args(argv)

    # Resolve the hex string: --hex flag > environment variable > stub
    hex_str = args.hex
    if hex_str is None:
        hex_str = os.environ.get("NICE_FLOR_S_RAINBOW_TABLE")

    table_bytes = parse_hex_table(hex_str) if hex_str else None

    if table_bytes is not None:
        source = generate_populated_source(table_bytes)
        noun = "32-byte rainbow table embedded"
    else:
        if hex_str is not None:
            print(
                f"Warning: could not parse hex string as 32 bytes — "
                f"generating NULL stub.",
                file=sys.stderr,
            )
        source = _STUB_TEMPLATE
        noun = "stub (no table embedded)"

    # Write output
    try:
        with open(args.output, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(source)
    except OSError as exc:
        print(f"Error writing '{args.output}': {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"Generated '{args.output}' — {noun}.", file=sys.stderr)


if __name__ == "__main__":
    main()
