/* See COPYING.txt for license details. */

/**
 * @file  subghz_keeloq_mfkeys.h
 * @brief KeeLoq manufacturer (master) key store — SD-card backed lookup.
 *
 * The preferred keystore format is an AES-256-CBC encrypted binary file:
 *   0:/SUBGHZ/keeloq_mfcodes.enc
 *
 * Use ``scripts/encrypt_keeloq_keys.py`` to produce this file from
 * RocketGod's SubGHz Toolkit output or from compact plaintext — then copy
 * only the ``.enc`` file to the SD card (the plaintext never needs to be
 * placed on the card).
 *
 * **Automatic migration**: if only a plaintext ``keeloq_mfcodes`` file
 * exists (legacy workflow), ``keeloq_mfkeys_load()`` will load it, write
 * the encrypted file, and delete the plaintext automatically.
 *
 * **Plaintext fallback** (legacy, still accepted):
 *   0:/SUBGHZ/keeloq_mfcodes
 *
 * Two text formats are accepted inside the encrypted payload (and in the
 * plaintext fallback file):
 *
 * **Compact format** (one entry per line, '#' comments ignored):
 *   AABBCCDDEEFFAABB:1:ManufacturerName   (Simple Learning)
 *   AABBCCDDEEFFAABB:2:ManufacturerName   (Normal Learning)
 *   AABBCCDDEEFFAABB:3:ManufacturerName   (Secure Learning)
 *
 * **RocketGod format** (multi-line, as exported by
 *   RocketGod's SubGHz Toolkit for Flipper Zero):
 *   Manufacturer: ManufacturerName
 *   Key (Hex):    AABBCCDDEEFFAABB
 *   Key (Dec):    <decimal — ignored>
 *   Type:         1
 *   ------------------------------------
 *
 * Both formats may coexist in the same file.  Use
 * ``scripts/encrypt_keeloq_keys.py`` to convert and encrypt in one step.
 * ``scripts/convert_keeloq_keys.py`` is kept for backward compatibility.
 *
 * Usage:
 *   1. Call keeloq_mfkeys_load() once at startup (or on demand).
 *   2. Call keeloq_mfkeys_find() to look up a key by manufacturer name.
 *   3. Call keeloq_mfkeys_free() to release the loaded table.
 */

#pragma once

#include <stdint.h>
#include <stdbool.h>

/*============================================================================*/
/* Types                                                                      */
/*============================================================================*/

/** KeeLoq device-key derivation mode. */
typedef enum {
    KEELOQ_LEARN_SIMPLE  = 1,   /**< Simple XOR learning */
    KEELOQ_LEARN_NORMAL  = 2,   /**< Normal learning (most common) */
    KEELOQ_LEARN_SECURE  = 3,   /**< Secure learning (seed-based) */
} KeeLoqLearnType;

/** One manufacturer key table entry. */
typedef struct {
    char           name[48];     /**< Manufacturer name (null-terminated) */
    uint64_t       key;          /**< 64-bit master key */
    KeeLoqLearnType learn_type;  /**< Derivation mode */
} KeeLoqMfrEntry;

/*============================================================================*/
/* Build-time embedded keys                                                   */
/*============================================================================*/

/**
 * Compact-text keystore embedded at build time from a private key vault.
 *
 * Defined in Sub_Ghz/subghz_keeloq_mfkeys_builtin.c, which is generated by
 * scripts/gen_keeloq_mfkeys_builtin.py during private/CI builds.
 * The version committed to the public repository has this set to NULL with
 * keeloq_mfkeys_builtin_len == 0, causing keeloq_mfkeys_load() to fall back
 * to the SD card keystore.
 *
 * When non-NULL and non-zero, keeloq_mfkeys_load() uses this data directly
 * and does NOT consult the SD card (Flipper-compatible behaviour).
 */
extern const char * const keeloq_mfkeys_builtin_text;

/** Number of bytes in keeloq_mfkeys_builtin_text (0 if no keys embedded). */
extern const uint32_t     keeloq_mfkeys_builtin_len;

/*============================================================================*/
/* SD-card keystore paths                                                     */
/*============================================================================*/

/**
 * Path on the SD card where the AES-256-CBC encrypted keystore is stored.
 * This is the preferred format — use scripts/encrypt_keeloq_keys.py to
 * produce this file from RocketGod toolkit output or compact plaintext.
 * Override at compile time (e.g. for host-side tests) with -D.
 */
#ifndef KEELOQ_MFKEYS_ENC_PATH
#define KEELOQ_MFKEYS_ENC_PATH  "0:/SUBGHZ/keeloq_mfcodes.enc"
#endif

/**
 * Path on the SD card where the legacy plaintext keystore is located.
 * Accepted as a fallback; automatically migrated to the encrypted format
 * by keeloq_mfkeys_load() and then deleted.
 * Override at compile time (e.g. for host-side tests) with -D.
 */
#ifndef KEELOQ_MFKEYS_PATH
#define KEELOQ_MFKEYS_PATH  "0:/SUBGHZ/keeloq_mfcodes"
#endif

/*============================================================================*/
/* API                                                                        */
/*============================================================================*/

/**
 * @brief  Load the manufacturer key table.
 *
 * Priority order:
 *   1. Build-time embedded keys (keeloq_mfkeys_builtin_text / _len) — highest
 *      priority.  If the firmware was built with a private key vault, the keys
 *      are compiled into flash; the SD card is NOT consulted.  This matches
 *      the Flipper Zero behaviour where manufacturer keys are never exposed as
 *      a file on removable media.
 *   2. AES-256-CBC encrypted SD card keystore (keeloq_mfcodes.enc).
 *   3. Legacy plaintext SD card file (keeloq_mfcodes) — auto-migrated to the
 *      encrypted format and then deleted.
 *
 * @return true if any key source was opened and parsed (even if 0 entries
 *         were found); false if no source could be accessed.
 */
bool keeloq_mfkeys_load(void);

/**
 * @brief  Load the manufacturer key table from the encrypted keystore.
 *
 * Opens KEELOQ_MFKEYS_ENC_PATH, validates the "M1KL" magic and version,
 * decrypts the AES-256-CBC payload with the built-in product key, and
 * feeds the result to keeloq_mfkeys_load_text().
 *
 * @return true on success (even if 0 entries were found after decryption),
 *         false if the file is absent, corrupt, or decryption fails.
 */
bool keeloq_mfkeys_load_encrypted(void);

/**
 * @brief  Save the currently loaded key table as an encrypted keystore.
 *
 * Serialises the in-memory table to compact "HEX:TYPE:NAME\n" text,
 * encrypts it with AES-256-CBC using the built-in product key, and writes
 * the binary to KEELOQ_MFKEYS_ENC_PATH.
 *
 * @return true on success, false if nothing is loaded or the write fails.
 */
bool keeloq_mfkeys_save_encrypted(void);

/**
 * @brief  Parse a null-terminated text string into the manufacturer key table.
 *
 * Parses @p text as if it were the contents of the keeloq_mfcodes file.
 * Supports both the compact ``HEX:TYPE:NAME`` format and the RocketGod
 * SubGHz Toolkit multi-line format.  The previous table (if any) is freed
 * first.
 *
 * This function has no hardware dependencies and is suitable for host-side
 * unit tests.
 *
 * @param[in] text  Null-terminated string containing keystore content.
 * @return true on success (even if zero valid entries were found),
 *         false if @p text is NULL or memory allocation fails.
 */
bool keeloq_mfkeys_load_text(const char *text);

/**
 * @brief  Free the in-memory manufacturer key table.
 *         Safe to call even if the table was never loaded.
 */
void keeloq_mfkeys_free(void);

/**
 * @brief  Look up a manufacturer key by name (case-insensitive).
 *
 * @param[in]  name    Manufacturer name to search for.
 * @param[out] entry   On success, filled with the matching entry.
 * @return true if found, false otherwise.
 */
bool keeloq_mfkeys_find(const char *name, KeeLoqMfrEntry *entry);

/**
 * @brief  Return the number of entries currently loaded.
 */
uint32_t keeloq_mfkeys_count(void);
