# CMake generated Testfile for 
# Source directory: /home/runner/work/M1/M1/tests
# Build directory: /home/runner/work/M1/M1/build_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(bit_util "/home/runner/work/M1/M1/build_test/test_bit_util")
set_tests_properties(bit_util PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;71;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(esp32_caps "/home/runner/work/M1/M1/build_test/test_esp32_caps")
set_tests_properties(esp32_caps PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;103;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(esp32_feature_map "/home/runner/work/M1/M1/build_test/test_esp32_feature_map")
set_tests_properties(esp32_feature_map PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;129;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(battery_soc "/home/runner/work/M1/M1/build_test/test_battery_soc")
set_tests_properties(battery_soc PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;148;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(bt_spam_counts "/home/runner/work/M1/M1/build_test/test_bt_spam_counts")
set_tests_properties(bt_spam_counts PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;172;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(bq27421_init "/home/runner/work/M1/M1/build_test/test_bq27421_init")
set_tests_properties(bq27421_init PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;198;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(watchdog_boot_loop "/home/runner/work/M1/M1/build_test/test_watchdog_boot_loop")
set_tests_properties(watchdog_boot_loop PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;215;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(json_mini "/home/runner/work/M1/M1/build_test/test_json_mini")
set_tests_properties(json_mini PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;234;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(flipper_subghz "/home/runner/work/M1/M1/build_test/test_flipper_subghz")
set_tests_properties(flipper_subghz PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;256;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(flipper_file "/home/runner/work/M1/M1/build_test/test_flipper_file")
set_tests_properties(flipper_file PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;276;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_raw_capture_alloc "/home/runner/work/M1/M1/build_test/test_subghz_raw_capture_alloc")
set_tests_properties(subghz_raw_capture_alloc PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;296;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_read_raw_status "/home/runner/work/M1/M1/build_test/test_subghz_read_raw_status")
set_tests_properties(subghz_read_raw_status PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;317;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(esp32_subghz_lifecycle "/home/runner/work/M1/M1/build_test/test_esp32_subghz_lifecycle")
set_tests_properties(esp32_subghz_lifecycle PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;334;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(submenu_widget_rollout "/home/runner/work/M1/M1/build_test/test_submenu_widget_rollout")
set_tests_properties(submenu_widget_rollout PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;352;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(esp32_main_deinit_releases_legacy_task "/home/runner/work/M1/M1/build_test/test_esp32_main_deinit_releases_legacy_task")
set_tests_properties(esp32_main_deinit_releases_legacy_task PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;373;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_registry "/home/runner/work/M1/M1/build_test/test_subghz_registry")
set_tests_properties(subghz_registry PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;401;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_freq_presets "/home/runner/work/M1/M1/build_test/test_subghz_freq_presets")
set_tests_properties(subghz_freq_presets PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;423;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_history "/home/runner/work/M1/M1/build_test/test_subghz_history")
set_tests_properties(subghz_history PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;444;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_key_encoder "/home/runner/work/M1/M1/build_test/test_subghz_key_encoder")
set_tests_properties(subghz_key_encoder PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;469;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_protocol_decode "/home/runner/work/M1/M1/build_test/test_subghz_protocol_decode")
set_tests_properties(subghz_protocol_decode PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;502;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(firecracker_cm17a "/home/runner/work/M1/M1/build_test/test_firecracker_cm17a")
set_tests_properties(firecracker_cm17a PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;528;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_raw_line_parser "/home/runner/work/M1/M1/build_test/test_subghz_raw_line_parser")
set_tests_properties(subghz_raw_line_parser PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;546;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_raw_decoder "/home/runner/work/M1/M1/build_test/test_subghz_raw_decoder")
set_tests_properties(subghz_raw_decoder PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;565;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_mod_suggest "/home/runner/work/M1/M1/build_test/test_subghz_mod_suggest")
set_tests_properties(subghz_mod_suggest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;583;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rf_repetition "/home/runner/work/M1/M1/build_test/test_rf_repetition")
set_tests_properties(rf_repetition PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;602;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rf_fingerprint "/home/runner/work/M1/M1/build_test/test_rf_fingerprint")
set_tests_properties(rf_fingerprint PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;615;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rf_protocol_db "/home/runner/work/M1/M1/build_test/test_rf_protocol_db")
set_tests_properties(rf_protocol_db PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;626;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rf_match "/home/runner/work/M1/M1/build_test/test_rf_match")
set_tests_properties(rf_match PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;638;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rf_fingerprint_24 "/home/runner/work/M1/M1/build_test/test_rf_fingerprint_24")
set_tests_properties(rf_fingerprint_24 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;656;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rf_sweep "/home/runner/work/M1/M1/build_test/test_rf_sweep")
set_tests_properties(rf_sweep PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;669;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rf_sweep_display "/home/runner/work/M1/M1/build_test/test_rf_sweep_display")
set_tests_properties(rf_sweep_display PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;682;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rf_scan_plan "/home/runner/work/M1/M1/build_test/test_rf_scan_plan")
set_tests_properties(rf_scan_plan PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;697;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rf_ook_fsk "/home/runner/work/M1/M1/build_test/test_rf_ook_fsk")
set_tests_properties(rf_ook_fsk PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;709;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rf_timing_capture "/home/runner/work/M1/M1/build_test/test_rf_timing_capture")
set_tests_properties(rf_timing_capture PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;721;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_decode_try_fn "/home/runner/work/M1/M1/build_test/test_subghz_decode_try_fn")
set_tests_properties(subghz_decode_try_fn PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;752;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_protocol_ignore "/home/runner/work/M1/M1/build_test/test_subghz_protocol_ignore")
set_tests_properties(subghz_protocol_ignore PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;771;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_playlist_parser "/home/runner/work/M1/M1/build_test/test_subghz_playlist_parser")
set_tests_properties(subghz_playlist_parser PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;790;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_block_decoder "/home/runner/work/M1/M1/build_test/test_subghz_block_decoder")
set_tests_properties(subghz_block_decoder PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;808;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_block_encoder "/home/runner/work/M1/M1/build_test/test_subghz_block_encoder")
set_tests_properties(subghz_block_encoder PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;826;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_manchester_codec "/home/runner/work/M1/M1/build_test/test_subghz_manchester_codec")
set_tests_properties(subghz_manchester_codec PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;844;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(datatypes_utils "/home/runner/work/M1/M1/build_test/test_datatypes_utils")
set_tests_properties(datatypes_utils PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;861;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(menu_layout "/home/runner/work/M1/M1/build_test/test_menu_layout")
set_tests_properties(menu_layout PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;879;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(esp_queue "/home/runner/work/M1/M1/build_test/test_esp_queue")
set_tests_properties(esp_queue PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;902;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(flipper_rfid "/home/runner/work/M1/M1/build_test/test_flipper_rfid")
set_tests_properties(flipper_rfid PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;925;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(flipper_ir "/home/runner/work/M1/M1/build_test/test_flipper_ir")
set_tests_properties(flipper_ir PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;947;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(flipper_nfc "/home/runner/work/M1/M1/build_test/test_flipper_nfc")
set_tests_properties(flipper_nfc PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;969;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(lfrfid_manchester "/home/runner/work/M1/M1/build_test/test_lfrfid_manchester")
set_tests_properties(lfrfid_manchester PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;997;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(t5577_timing "/home/runner/work/M1/M1/build_test/test_t5577_timing")
set_tests_properties(t5577_timing PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1017;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(fw_source_filter "/home/runner/work/M1/M1/build_test/test_fw_source_filter")
set_tests_properties(fw_source_filter PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1036;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rpc_crc16 "/home/runner/work/M1/M1/build_test/test_rpc_crc16")
set_tests_properties(rpc_crc16 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1055;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rpc_parse "/home/runner/work/M1/M1/build_test/test_rpc_parse")
set_tests_properties(rpc_parse PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1075;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(file_browser "/home/runner/work/M1/M1/build_test/test_file_browser")
set_tests_properties(file_browser PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1095;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(http_client_parse "/home/runner/work/M1/M1/build_test/test_http_client_parse")
set_tests_properties(http_client_parse PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1119;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(settings_hex_color "/home/runner/work/M1/M1/build_test/test_settings_hex_color")
set_tests_properties(settings_hex_color PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1138;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(led_color_ease "/home/runner/work/M1/M1/build_test/test_led_color_ease")
set_tests_properties(led_color_ease PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1159;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rgb_backlight "/home/runner/work/M1/M1/build_test/test_rgb_backlight")
set_tests_properties(rgb_backlight PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1176;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(ir_signal_record "/home/runner/work/M1/M1/build_test/test_ir_signal_record")
set_tests_properties(ir_signal_record PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1200;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(esp32_progress "/home/runner/work/M1/M1/build_test/test_esp32_progress")
set_tests_properties(esp32_progress PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1216;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(fw_progress "/home/runner/work/M1/M1/build_test/test_fw_progress")
set_tests_properties(fw_progress PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1230;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(esp32_fw_update "/home/runner/work/M1/M1/build_test/test_esp32_fw_update")
set_tests_properties(esp32_fw_update PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1246;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(ir_search "/home/runner/work/M1/M1/build_test/test_ir_search")
set_tests_properties(ir_search PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1265;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(ir_cmd_parse "/home/runner/work/M1/M1/build_test/test_ir_cmd_parse")
set_tests_properties(ir_cmd_parse PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1284;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(ir_button_map "/home/runner/work/M1/M1/build_test/test_ir_button_map")
set_tests_properties(ir_button_map PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1304;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(system_dashboard "/home/runner/work/M1/M1/build_test/test_system_dashboard")
set_tests_properties(system_dashboard PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1323;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(hex_viewer "/home/runner/work/M1/M1/build_test/test_hex_viewer")
set_tests_properties(hex_viewer PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1338;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(nfc_poller "/home/runner/work/M1/M1/build_test/test_nfc_poller")
set_tests_properties(nfc_poller PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1355;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(clock "/home/runner/work/M1/M1/build_test/test_clock")
set_tests_properties(clock PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1371;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_secplus_v1 "/home/runner/work/M1/M1/build_test/test_subghz_secplus_v1")
set_tests_properties(subghz_secplus_v1 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1389;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(esl_proto "/home/runner/work/M1/M1/build_test/test_esl_proto")
set_tests_properties(esl_proto PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1406;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(cc1101_fec "/home/runner/work/M1/M1/build_test/test_cc1101_fec")
set_tests_properties(cc1101_fec PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1427;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_keeloq "/home/runner/work/M1/M1/build_test/test_subghz_keeloq")
set_tests_properties(subghz_keeloq PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1456;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(keeloq_mfkeys_enc "/home/runner/work/M1/M1/build_test/test_keeloq_mfkeys_enc")
set_tests_properties(keeloq_mfkeys_enc PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1492;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_new_remote_gen "/home/runner/work/M1/M1/build_test/test_subghz_new_remote_gen")
set_tests_properties(subghz_new_remote_gen PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1513;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_create_proto "/home/runner/work/M1/M1/build_test/test_subghz_create_proto")
set_tests_properties(subghz_create_proto PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1532;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_hex_editor "/home/runner/work/M1/M1/build_test/test_subghz_hex_editor")
set_tests_properties(subghz_hex_editor PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1551;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_keeloq_create "/home/runner/work/M1/M1/build_test/test_subghz_keeloq_create")
set_tests_properties(subghz_keeloq_create PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1574;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_signal_fields "/home/runner/work/M1/M1/build_test/test_subghz_signal_fields")
set_tests_properties(subghz_signal_fields PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1600;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_nice_flor_s "/home/runner/work/M1/M1/build_test/test_subghz_nice_flor_s")
set_tests_properties(subghz_nice_flor_s PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1618;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_came_atomo "/home/runner/work/M1/M1/build_test/test_subghz_came_atomo")
set_tests_properties(subghz_came_atomo PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1636;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_alutech_at_4n "/home/runner/work/M1/M1/build_test/test_subghz_alutech_at_4n")
set_tests_properties(subghz_alutech_at_4n PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1654;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_signal_format "/home/runner/work/M1/M1/build_test/test_subghz_signal_format")
set_tests_properties(subghz_signal_format PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1679;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_read_raw_state "/home/runner/work/M1/M1/build_test/test_subghz_read_raw_state")
set_tests_properties(subghz_read_raw_state PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1700;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_rssi_history "/home/runner/work/M1/M1/build_test/test_subghz_rssi_history")
set_tests_properties(subghz_rssi_history PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1719;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_blocking_replay_contract "/home/runner/work/M1/M1/build_test/test_subghz_blocking_replay_contract")
set_tests_properties(subghz_blocking_replay_contract PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1736;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(keeloq_mfkeys_builtin "/home/runner/work/M1/M1/build_test/test_keeloq_mfkeys_builtin")
set_tests_properties(keeloq_mfkeys_builtin PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1771;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(badusb_parser "/home/runner/work/M1/M1/build_test/test_badusb_parser")
set_tests_properties(badusb_parser PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1786;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(badusb_migration "/home/runner/work/M1/M1/build_test/test_badusb_migration")
set_tests_properties(badusb_migration PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1799;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(badusb_typing_speed "/home/runner/work/M1/M1/build_test/test_badusb_typing_speed")
set_tests_properties(badusb_typing_speed PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1812;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_haldelay_free "/home/runner/work/M1/M1/build_test/test_wifi_haldelay_free")
set_tests_properties(wifi_haldelay_free PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1825;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_scan_status_nonblocking "/home/runner/work/M1/M1/build_test/test_wifi_scan_status_nonblocking")
set_tests_properties(wifi_scan_status_nonblocking PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1840;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_ux_restructure "/home/runner/work/M1/M1/build_test/test_wifi_ux_restructure")
set_tests_properties(wifi_ux_restructure PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1853;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(esp32_dag_gating_audit "/home/runner/work/M1/M1/build_test/test_esp32_dag_gating_audit")
set_tests_properties(esp32_dag_gating_audit PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1866;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_autosave "/home/runner/work/M1/M1/build_test/test_subghz_autosave")
set_tests_properties(subghz_autosave PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1881;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(nfc_ndef_encode "/home/runner/work/M1/M1/build_test/test_nfc_ndef_encode")
set_tests_properties(nfc_ndef_encode PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1896;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(nfc_ndef_parse "/home/runner/work/M1/M1/build_test/test_nfc_ndef_parse")
set_tests_properties(nfc_ndef_parse PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1918;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(nfc_card_info "/home/runner/work/M1/M1/build_test/test_nfc_card_info")
set_tests_properties(nfc_card_info PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1940;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(nfc_file_parse "/home/runner/work/M1/M1/build_test/test_nfc_file_parse")
set_tests_properties(nfc_file_parse PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1961;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(mfc_layout "/home/runner/work/M1/M1/build_test/test_mfc_layout")
set_tests_properties(mfc_layout PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;1983;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(mfc_crypto1 "/home/runner/work/M1/M1/build_test/test_mfc_crypto1")
set_tests_properties(mfc_crypto1 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2007;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(mfkey32 "/home/runner/work/M1/M1/build_test/test_mfkey32")
set_tests_properties(mfkey32 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2031;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(nfc_classify "/home/runner/work/M1/M1/build_test/test_nfc_classify")
set_tests_properties(nfc_classify PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2051;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(nfc_ntag "/home/runner/work/M1/M1/build_test/test_nfc_ntag")
set_tests_properties(nfc_ntag PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2071;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(file_util "/home/runner/work/M1/M1/build_test/test_file_util")
set_tests_properties(file_util PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2086;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(crypto "/home/runner/work/M1/M1/build_test/test_crypto")
set_tests_properties(crypto PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2102;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(music_parser "/home/runner/work/M1/M1/build_test/test_music_parser")
set_tests_properties(music_parser PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2117;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_txrx_state "/home/runner/work/M1/M1/build_test/test_subghz_txrx_state")
set_tests_properties(subghz_txrx_state PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2131;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_scene_state "/home/runner/work/M1/M1/build_test/test_subghz_scene_state")
set_tests_properties(subghz_scene_state PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2145;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_submenu_model "/home/runner/work/M1/M1/build_test/test_subghz_submenu_model")
set_tests_properties(subghz_submenu_model PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2159;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_endless_tx "/home/runner/work/M1/M1/build_test/test_subghz_endless_tx")
set_tests_properties(subghz_endless_tx PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2173;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_static_tx "/home/runner/work/M1/M1/build_test/test_subghz_static_tx")
set_tests_properties(subghz_static_tx PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2187;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_tx_wave_anim "/home/runner/work/M1/M1/build_test/test_subghz_tx_wave_anim")
set_tests_properties(subghz_tx_wave_anim PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2201;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_scene_polish "/home/runner/work/M1/M1/build_test/test_subghz_scene_polish")
set_tests_properties(subghz_scene_polish PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2217;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_transmitter_ctl "/home/runner/work/M1/M1/build_test/test_subghz_transmitter_ctl")
set_tests_properties(subghz_transmitter_ctl PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2231;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_button_caps "/home/runner/work/M1/M1/build_test/test_subghz_button_caps")
set_tests_properties(subghz_button_caps PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2247;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(subghz_button_override "/home/runner/work/M1/M1/build_test/test_subghz_button_override")
set_tests_properties(subghz_button_override PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2263;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(memmgr "/home/runner/work/M1/M1/build_test/test_memmgr")
set_tests_properties(memmgr PROPERTIES  ENVIRONMENT "ASAN_OPTIONS=allocator_may_return_null=1" _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2283;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(elf_alloc_budget "/home/runner/work/M1/M1/build_test/test_elf_alloc_budget")
set_tests_properties(elf_alloc_budget PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2305;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_ap_record "/home/runner/work/M1/M1/build_test/test_wifi_ap_record")
set_tests_properties(wifi_ap_record PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2319;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_ntp_parse "/home/runner/work/M1/M1/build_test/test_wifi_ntp_parse")
set_tests_properties(wifi_ntp_parse PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2333;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_status_msg "/home/runner/work/M1/M1/build_test/test_wifi_status_msg")
set_tests_properties(wifi_status_msg PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2347;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_scan_fail_msg "/home/runner/work/M1/M1/build_test/test_wifi_scan_fail_msg")
set_tests_properties(wifi_scan_fail_msg PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2360;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(esp32_spi_bin "/home/runner/work/M1/M1/build_test/test_esp32_spi_bin")
set_tests_properties(esp32_spi_bin PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2373;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_ch_analysis "/home/runner/work/M1/M1/build_test/test_wifi_ch_analysis")
set_tests_properties(wifi_ch_analysis PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2387;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_at_scan "/home/runner/work/M1/M1/build_test/test_wifi_at_scan")
set_tests_properties(wifi_at_scan PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2401;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_mac_utils "/home/runner/work/M1/M1/build_test/test_wifi_mac_utils")
set_tests_properties(wifi_mac_utils PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2415;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_file_utils "/home/runner/work/M1/M1/build_test/test_wifi_file_utils")
set_tests_properties(wifi_file_utils PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2429;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_selection "/home/runner/work/M1/M1/build_test/test_wifi_selection")
set_tests_properties(wifi_selection PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2444;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(wifi_deauth_cmd "/home/runner/work/M1/M1/build_test/test_wifi_deauth_cmd")
set_tests_properties(wifi_deauth_cmd PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2460;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(proto_pirate_timing "/home/runner/work/M1/M1/build_test/test_proto_pirate_timing")
set_tests_properties(proto_pirate_timing PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2474;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(ir_ux_polish "/home/runner/work/M1/M1/build_test/test_ir_ux_polish")
set_tests_properties(ir_ux_polish PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2487;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(irmp_decode "/home/runner/work/M1/M1/build_test/test_irmp_decode")
set_tests_properties(irmp_decode PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2502;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(esp32_idle "/home/runner/work/M1/M1/build_test/test_esp32_idle")
set_tests_properties(esp32_idle PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2516;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(rf_smart_scan "/home/runner/work/M1/M1/build_test/test_rf_smart_scan")
set_tests_properties(rf_smart_scan PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2531;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(espnow_peer_session "/home/runner/work/M1/M1/build_test/test_espnow_peer_session")
set_tests_properties(espnow_peer_session PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2550;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(espnow_file_transfer "/home/runner/work/M1/M1/build_test/test_espnow_file_transfer")
set_tests_properties(espnow_file_transfer PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2569;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
add_test(espnow_tictactoe "/home/runner/work/M1/M1/build_test/test_espnow_tictactoe")
set_tests_properties(espnow_tictactoe PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/M1/M1/tests/CMakeLists.txt;2588;add_test;/home/runner/work/M1/M1/tests/CMakeLists.txt;0;")
